routes:
  /:
    data: page.home
    template: home
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /:
    permalink: /{primary_tag}/{slug}/
    template: index
  /all/:
    permalink: /{primary_tag}/{slug}/
    template: index

taxonomies:
  tag: /{slug}/
  author: /author/{slug}/
